# Generated by Django 5.2.6 on 2025-09-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_DB',
            fields=[
                ('Car_Name', models.CharField(max_length=40)),
                ('Number_plate', models.CharField(primary_key=True, serialize=False)),
                ('Car_color', models.CharField(max_length=30)),
                ('Car_model', models.IntegerField()),
                ('Car_capacity', models.IntegerField()),
            ],
        ),
    ]
